version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      - echo Initializing environment
      - export CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token \
          --domain nextwork \
          --domain-owner 640168441707 \
          --region us-west-2 \
          --query authorizationToken \
          --output text)
      - echo "<settings><servers><server><id>nextwork-nextwork-devops-cicd</id><username>aws</username><password>${CODEARTIFACT_AUTH_TOKEN}</password></server></servers></settings>" > settings.xml
  build:
    commands:
      - echo Build started on `date`
      - mvn -s settings.xml compile
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn -s settings.xml package

artifacts:
  files:
    - target/nextwork-web-project.war

